FROM continuumio/miniconda3

# Python
RUN conda install python=3.6
RUN conda install -c conda-forge jupyterlab
RUN conda install -c conda-forge papermill
RUN conda install tornado==5.0.2
RUN conda install -c conda-forge gitpython

# R 
RUN conda install -c r r-irkernel
RUN conda install -c r r-jsonlite
RUN conda install -c conda-forge r-rserve
RUN conda install -c conda-forge r-mlmetrics
RUN conda install -c conda-forge r-caret





